### ISSUE TITLE
Specify secrets output directory 

### ISSUE THREAD

**Issue by wellencamass** [ThreatUnkown/jsubfinder#15]
Hello, hiddengearz! 

Is it possible to specify directory to store secrets?

Right now its ```os.OpenFile("secrets_"+OutputFile``` and its impossible to use because if I open file located in the another path it wont work as expected
For example: 
```
/tmp/jsubfinder.binary search --crawl -t 10 -s --sig '/tmp/.jsf_signatures.yaml' -f /dockerresults/httpx.txt -o /dockerresults/js.txt
```

Will give an error 
```
 open secrets_/dockerresults/js.txt: no such file or directory
 ```  
which is 100% right , it cant open absolute url like that

So for example i would like to have something like ``` -store-secrets-dir /dockerresults/secrets ```

Hope to hear your answer soon,
Regards, wellenc :)

**Comment by hiddengearz** [comment]
This has been resolved in 557fd90d99fa247e7bb3013115e08e2c3e666b9d

`-s` now takes a string argument for the location of the secrets file.

`jsubfinder search -u www.youtube.com -s /home/user/somefolder/secrests_test.txt`
